### PR TITLE
New version of MathematicalSystems

### PR DESCRIPTION
**Pull request by schillic**
TagBot does not trigger anymore. Maybe wake it up?

EDIT: The build error in v1.8 x86 seems unrelated:
```julia
InexactError: trunc(Int32, -1.0507929548530072e199)
```

### CODE REVIEW

**Comment by blegat** [comment]
Thanks, there are updates to do in the examples as well

**Comment by schillic** [comment]
Done! But there is a new build error on v1.8.3:

```julia
Failed to precompile MappedArrays
```

Again I think this is independent of this PR.

**Comment by schillic** [comment]
I deactivated `depwarn: error` on CI to fix the build. @blegat let me know what you think.

**Comment by blegat** [comment]
Thanks!

**Pull request merged**
